## 10. Linear Algebra

| Function | Description |
|----------|-------------|
| `A @ B` | Matrix multiplication |
| `np.linalg.det(A)` | Determinant |
| `np.linalg.inv(A)` | Inverse |
| `np.linalg.solve(A,b)` | Solve Ax=b |
| `np.linalg.eig(A)` | Eigenvalues & vectors |
| `np.linalg.svd(A)` | SVD |
| `np.linalg.norm(A)` | Norm |
| `np.linalg.lstsq(A,b)` | Least-squares |
| `np.trace(A)` | Diagonal sum |

In [1]:
import numpy as np

In [3]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print('A @ B (matmul):\n',  A @ B)
print('A * B (element):\n', A * B)   # NOT matmul

A @ B (matmul):
 [[19 22]
 [43 50]]
A * B (element):
 [[ 5 12]
 [21 32]]


In [4]:
M = np.array([[2,1],[5,3]])
print(f'det(M) = {np.linalg.det(M):.2f}')

inv = np.linalg.inv(M)

print('inv(M):\n', inv)
print('M @ inv (should be I):\n', (M@inv).round(10))

det(M) = 1.00
inv(M):
 [[ 3. -1.]
 [-5.  2.]]
M @ inv (should be I):
 [[1. 0.]
 [0. 1.]]


In [5]:
# Solve linear system: 2x+y=5, 5x+3y=13

A_sys = np.array([[2,1],[5,3]])
b_sys = np.array([5,13])

x_sol = np.linalg.solve(A_sys, b_sys)

print(f'Solution x={x_sol[0]:.2f}, y={x_sol[1]:.2f}')
print(f'Verify A@x = {A_sys@x_sol}')

Solution x=2.00, y=1.00
Verify A@x = [ 5. 13.]


In [6]:
# Eigenvalues

C = np.array([[4,2],[1,3]])

evals, evecs = np.linalg.eig(C)
print('Eigenvalues:', evals)

Eigenvalues: [5. 2.]


In [7]:
# Norms

v = np.array([3,4])

print(f'L2 norm: {np.linalg.norm(v):.2f}')    # 5.0
print(f'L1 norm: {np.linalg.norm(v,ord=1):.2f}') # 7.0

L2 norm: 5.00
L1 norm: 7.00


In [8]:
# Linear regression via lstsq

x_d = np.array([1,2,3,4,5,6,7,8,9,10],dtype=float)
y_d = np.array([2.1,3.9,6.2,7.8,10.1,11.9,14.3,15.8,18.2,20.1])

A_lr = np.column_stack([x_d, np.ones_like(x_d)])
coeffs,_,_,_ = np.linalg.lstsq(A_lr, y_d, rcond=None)
m_r, c_r = coeffs

print(f'Regression: y = {m_r:.4f}x + {c_r:.4f}')

y_pred = m_r*x_d + c_r
r2 = 1 - np.sum((y_d-y_pred)**2)/np.sum((y_d-y_d.mean())**2)

print(f'R² = {r2:.4f}')

Regression: y = 2.0085x + -0.0067
R² = 0.9992
