## 2. Creating Array

| Function | Description |
|----------|-------------|
| `np.array([...])` | From Python list/tuple |
| `np.zeros(shape)` | All zeros |
| `np.ones(shape)` | All ones |
| `np.full(shape, val)` | All same value |
| `np.eye(n)` | Identity matrix |
| `np.arange(start,stop,step)` | Like `range()` |
| `np.linspace(start,stop,n)` | Evenly spaced |
| `np.random.default_rng()` | Modern RNG API |

In [1]:
import numpy as np

## Creating Array

In [6]:
# 1-D Array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
# 2-D Array
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [8]:
# 3-D Array
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Factory functions

In [13]:
# np.zeros(shape) - 0

zero_arr = np.zeros((3,4))
print('zeros(3,4):\n', zero_arr)

zeros(3,4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
# np.ones(shape) - 1

ones_arr = np.ones((2,3))
print('ones(2,3):\n',ones_arr)

ones(2,3):
 [[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# full(shape, value)

full_arr = np.full((2,3), 5)
print('full(2,3,5):\n', full_arr)

full(2,3,5):
 [[5 5 5]
 [5 5 5]]


In [17]:
# Creating Identity Matrix
# np.eye()

id_matrix = np.eye(3)
print('eye(3) [Identity Matrix]:\n', id_matrix)

eye(3) [Identity Matrix]:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# creating sequence of numbers
# arange()
# arange(start,stop,step)

aranged_arr = np.arange(1,10,2)
print('arange(1,10,2):', aranged_arr)

arange(1,10,2): [1 3 5 7 9]


In [22]:
# Creating linspace array
# linspace(start,stop,no. of element)

lin_arr = np.linspace(0,1,6)
print('linspace(0,1,6):', lin_arr)

linspace(0,1,6): [0.  0.2 0.4 0.6 0.8 1. ]
