## 3. Numpy Basics

### Key array attributes
| Attribute | Meaning |
|-----------|--------|
| `.ndim` | Number of dimensions |
| `.shape` | Sizes per axis |
| `.size` | Total elements |
| `.dtype` | Element data type |
| `.nbytes` | Total bytes |

### NumPy dtypes
| dtype | Bytes |
|-------|-------|
| `int8/16/32/64` | 1/2/4/8 |
| `float32/64` | 4/8 |
| `complex64/128` | 8/16 |
| `bool` | 1 |

In [5]:
import numpy as np

In [6]:
# Shape
arr_2d = np.array([[1,2,3],
                  [4,5,6]])

print(arr_2d.shape)

(2, 3)


In [7]:
# Size
arr_2d = np.array([[10,20,30],
                  [40,50,60]])

print(arr_2d.size)

6


In [8]:
# Dimesnion
arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3], [4,5,6]])
arr_3d = np.array([[[1,2], [3,4], [5,6], [7,8]]])

print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


In [14]:
# Data type & Nbytes
arr = np.array([1,2,3])
print(arr.dtype)
print(arr.nbytes)

arr = np.array([1,2.5,3])
print(arr.dtype)
print(arr.nbytes)

int64
24
float64
24


In [15]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for name, arr in [('1-D',a1),('2-D',a2),('3-D',a3)]:
    print(f'{name}: ndim={arr.ndim}, shape={arr.shape}, size={arr.size}, dtype={arr.dtype}, nbytes={arr.nbytes}')

1-D: ndim=1, shape=(5,), size=5, dtype=int64, nbytes=40
2-D: ndim=2, shape=(2, 3), size=6, dtype=int64, nbytes=48
3-D: ndim=3, shape=(2, 2, 2), size=8, dtype=int64, nbytes=64


In [11]:
# Astype
arr = np.array([1.2, 2.5, 3.6])
print(arr.dtype)

int_arr = arr.astype(int)

print(int_arr)
print(int_arr.dtype)


float64
[1 2 3]
int64


In [16]:
# Type casting
x = np.array([1.7, 2.9, 3.1])
print('float64:', x)
print('as int :', x.astype(int))   # truncates

float64: [1.7 2.9 3.1]
as int : [1 2 3]


In [4]:
# dtypes
print('int8  :', np.array([1,2,3],dtype=np.int8),    ' bytes=', np.array([1,2,3],dtype=np.int8).nbytes)
print('float32:', np.array([1,2,3],dtype=np.float32),' bytes=', np.array([1,2,3],dtype=np.float32).nbytes)
print('bool  :', np.array([1,0,1,0],dtype=bool))

int8  : [1 2 3]  bytes= 3
float32: [1. 2. 3.]  bytes= 12
bool  : [ True False  True False]


In [17]:
# maths
arr = np.array([10,20,30])

print(arr + 5)
print(arr * 2)
print(arr ** 2)

[15 25 35]
[20 40 60]
[100 400 900]


In [18]:
# Aggregating Function
arr = np.array([10, 20, 30, 40, 50])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

150
30.0
10
50
14.142135623730951
200.0
