## 4. Indexing & Slicing

### Four indexing styles

**1. Basic indexing** - `arr[i]`, `arr[r, c]`  
**2. Slicing** - `arr[start:stop:step]`  
**3. Fancy indexing** - `arr[[0,2,4]]` - returns **copy**  
**4. Boolean masking** - `arr[arr > 5]` - returns **copy**  

### View vs Copy
| Operation | Returns |
|-----------|--------|
| Basic slice `arr[1:3]` | View |
| Fancy index `arr[[1,3]]` | Copy |
| Boolean mask `arr[arr>0]` | Copy |
| `.copy()` | Always copy |

> ⚠️ Modifying a **view** modifies the original array. Use `.copy()` when you need independence.

In [1]:
import numpy as np

## Indexing

In [10]:
# 1-D indexing
# array[index] -> 1d array

arr = np.array([10,20,30,40,50,60,70,80,90,100])
print('Array   :', a)
print('a[0]    :', arr[0]) #first element
print('a[1]    :', arr[1])
print('a[-1]   :', arr[-1]) #last element

Array   : [ 10  20  30  40  50  60  70  80  90 100]
a[0]    : 10
a[1]    : 20
a[-1]   : 100


## Slicing

In [25]:
# Slicing
# array[start:stop:step]

arr = np.array([1,2,3,4,5])

print('a[1:5]  :',arr[1:5]) # index 1 to 4
print('a[:4]  :',arr[:4]) # index 0 to 3
print('a[::2]  :',arr[::2]) # picks every 2nd element
print('a[::]  :',arr[::]) # full array
print('a[::-1]  :',arr[::-1]) # reversed array
print('a[0:4:2]  :',arr[0:4:2])

a[1:5]  : [2 3 4 5]
a[:4]  : [1 2 3 4]
a[::2]  : [1 3 5]
a[::]  : [1 2 3 4 5]
a[::-1]  : [5 4 3 2 1]
a[0:4:2]  : [1 3]


In [26]:
# 2-D indexing
# array[row,column] -> 2d array

m = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Matrix:\n', m)
print('m[1,2]    :', m[1,2]) # m12 (single element)
print('m[0,:]    :', m[0,:]) # 1st row
print('m[:,2]    :', m[:,2]) # 3rd column
print('m[0:2,1:3]:\n', m[0:2,1:3]) # submatrix

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
m[1,2]    : 7
m[0,:]    : [1 2 3 4]
m[:,2]    : [ 3  7 11]
m[0:2,1:3]:
 [[2 3]
 [6 7]]


## fancy Indexing

In [27]:
# select multiple element at once

arr = np.array([10,20,30,40,50])
print(arr[[0,2,4]])
print(arr[[1,3,4]])

[10 30 50]
[20 40 50]


In [28]:
m = np.array([[10,20,30],[40,50,60],[70,80,90],[11,22,33]])
print('Rows 0 and 2:\n', m[[0,2]])
print('Paired elements:', m[[0,1,2],[1,2,0]])

Rows 0 and 2:
 [[10 20 30]
 [70 80 90]]
Paired elements: [20 60 70]


## boolean masking

In [29]:
# Filtering

arr = np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [30]:
scores = np.array([45,82,61,38,75,90,55,88,42,70])
print('Scores         :', scores)
print('Passing (>=60) :', scores[scores >= 60])
print('Failing (<60)  :', scores[scores < 60])
print('70–89 range    :', scores[(scores>=70)&(scores<=89)])

Scores         : [45 82 61 38 75 90 55 88 42 70]
Passing (>=60) : [82 61 75 90 88 70]
Failing (<60)  : [45 38 55 42]
70–89 range    : [82 75 88 70]


In [31]:
# np.where

grade = np.where(scores >= 60, 'Pass', 'Fail')
print('Grades         :', grade)

Grades         : ['Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass']


In [32]:
# np.select - multiple conditions

conds   = [scores>=80, scores>=60, scores<60]
choices = ['Distinction','Pass','Fail']
result  = np.select(conds, choices)
print('np.select      :', result)

TypeError: Choicelist and default value do not have a common dtype: The DType <class 'numpy.dtypes._PyLongDType'> could not be promoted by <class 'numpy.dtypes.StrDType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyLongDType'>)

In [33]:
# Finding indices
print('Pass indices:', np.where(scores>=60)[0])
print('argmax      :', np.argmax(scores), '→', scores[np.argmax(scores)])
print('argmin      :', np.argmin(scores), '→', scores[np.argmin(scores)])

Pass indices: [1 2 4 5 7 9]
argmax      : 5 → 90
argmin      : 3 → 38
