## 5. Reshaping & Manipulation

Reshaping changes the **structure** without changing the data.

### Rules
- Total elements must remain the same: `3×4 = 12 = 2×6`
- Use `-1` as a wildcard - NumPy calculates it automatically

### Key functions
| Function | Description |
|----------|-------------|
| `arr.reshape(shape)` | New shape (same elements) |
| `arr.ravel()` | Flatten → view if possible |
| `arr.flatten()` | Flatten → always copy |
| `arr.T` | Transpose |
| `np.expand_dims(arr, axis)` | Add size-1 axis |

In [1]:
import numpy as np

In [5]:
# reshapr(rows,columns) specify new shape - if dimension match
# it doesnot create copy of arrau it only give view of new array
# convert 1d array in 2d or MultiD

arr = np.array([10,20,30,40,50,60])
reshape_arr = arr.reshape(2,3)

print(reshape_arr)
print(arr)


[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]


In [2]:
a = np.arange(1,13)
print('Original    :', a)
print('(3,4):\n',       a.reshape(3,4))
print('(2,6):\n',       a.reshape(2,6))
print('(-1,3)→4x3:\n',  a.reshape(-1,3))

Original    : [ 1  2  3  4  5  6  7  8  9 10 11 12]
(3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(2,6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(-1,3)→4x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# Flatteing array
# 1. Ravel()  2. Flatten()
# convert multiD or 2D in 1D

# ravel() -> view
# flatten() -> copy

arr_2d = np.array([[1,2],[3,5],[4,6]])
print(arr_2d.ravel())
print(arr_2d.flatten())

[1 2 3 5 4 6]
[[1 2]
 [3 5]
 [4 6]]
[1 2 3 5 4 6]
[[1 2]
 [3 5]
 [4 6]]


In [4]:
# Transpose

m2 = np.array([[1,2,3],[4,5,6]])
print('Original (2,3):\n', m2)
print('Transposed (3,2):\n', m2.T)

Original (2,3):
 [[1 2 3]
 [4 5 6]]
Transposed (3,2):
 [[1 4]
 [2 5]
 [3 6]]


In [5]:
# expand_dims & squeeze

v = np.array([1,2,3])
print('v.shape        :', v.shape)
print('row vector     :', np.expand_dims(v,0).shape)
print('col vector     :', np.expand_dims(v,1).shape)
print('squeeze(1,3,1,4):', np.squeeze(np.zeros((1,3,1,4))).shape)

v.shape        : (3,)
row vector     : (1, 3)
col vector     : (3, 1)
squeeze(1,3,1,4): (3, 4)
