## 6. Array Modification

### It include:
- add
- remove
- stack
- split

### Useful functions
| Function | Description |
|----------|-------------|
| `np.append / insert / delete` | Add/insert/remove elements |
| `np.unique(arr, return_counts)` | Unique values + counts |
| `np.sort / np.argsort` | Sort values / sort indices |
| `np.clip(arr, min, max)` | Cap to range |
| `np.round / ceil / floor` | Rounding |
| `np.flip / roll` | Reverse / rotate |
| `np.tile / repeat` | Tile / repeat elements |
| `np.pad` | Pad with values |
| `np.concatenate / hstack / vstack` | Join arrays |
| `np.split / hsplit / vsplit` | Split arrays |


In [2]:
import numpy as np

## Insert

In [3]:
# insert
# np.insert(array, index, value, axis=None)
# axis = 0 -> row-wise (vertical stacking)
# axis = 1 -> column-wise (horizontal stacking)

arr = np.array([10,20,30,40,50,60])
new_arr = np.insert(arr, 2, 25, axis=0)

print('Original array: ', arr)
print('Insert 25: ',new_arr)

Original array:  [10 20 30 40 50 60]
Insert 25:  [10 20 25 30 40 50 60]


In [6]:
arr_2d = np.array([[1,2], [3,4]])
print('Original array: \n',arr_2d)

new_arr_2d = np.insert(arr_2d, 2, [5,6], axis=0)
print('Insert in row: \n',new_arr_2d)

new_arr_2d = np.insert(arr_2d, 2, [5,6], axis=1)
print('Insert in col: \n',new_arr_2d)

Original array: 
 [[1 2]
 [3 4]]
Insert in row: 
 [[1 2]
 [3 4]
 [5 6]]
Insert in col: 
 [[1 2 5]
 [3 4 6]]


## Append

In [7]:
# Append -> add element at end
# np.appenf(arr, value)

arr = np.array([10,20,30])
new_arr = np.append(arr, [40,50])

print('Original array: ', arr)
print('Append : ', new_arr)

Original array:  [10 20 30]
Append :  [10 20 30 40 50]


## Concate

In [20]:
# Concate -> merge two array
# np.concatenate((array1, array1), axis = 0)

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print('Array 1: ', arr1)
print('Array 2: ', arr2)

new_arr = np.concatenate((arr1, arr2))
print('Concatenate Array :', new_arr)

Array 1:  [1 2 3]
Array 2:  [4 5 6]
Concatenate Array : [1 2 3 4 5 6]


## Delete

In [21]:
# Delete the value
# np.delete(array, index, axis=None)

arr = np.array([10,15,20,30])

new_arr = np.delete(arr, 1)
print('Original array: ', arr)
print('Delete[1] : ', new_arr)

Original array:  [10 15 20 30]
Delete[1] :  [10 20 30]


In [22]:
arr_2d = np.array([[10,15],[20,30]])
print('Original array: \n', arr_2d)

new_arr_2d = np.delete(arr_2d, 0, axis=0)
print('Delete in row : \n',new_arr_2d)

new_arr_2d = np.delete(arr_2d, 0, axis=1)
print('Delete in col : \n',new_arr_2d)

Original array: 
 [[10 15]
 [20 30]]
Delete in row : 
 [[20 30]]
Delete in col : 
 [[15]
 [30]]


## Stacking

In [23]:
# Stacking is done in two way 1. Vertically  2. Horizontally
# vstack() -> row wise
# hstack() -> column wise

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print('Array 1: ', arr1)
print('Array 2: ', arr2)

vstack_arr = np.vstack((arr1, arr2))
print('Vertically Stacking : \n', vstack_arr)

hstack_arr = np.hstack((arr1, arr2))
print('Horizontally Stacking : \n',hstack_arr)

Array 1:  [1 2 3]
Array 2:  [4 5 6]
Vertically Stacking : 
 [[1 2 3]
 [4 5 6]]
Horizontally Stacking : 
 [1 2 3 4 5 6]


## Spliting

In [24]:
# Splitting -> dividing the array 
# np.split() -> in equal parts
# np.hsplit() -> horizontallly split
# np.vsplit() -> vertically split

arr = np.array([10,20,30,40,50,60])
print('Original array: ', arr)

split_arr = np.split(arr, 2)
print('Split array in 2 : \n', split_arr)

split_arr = np.split(arr, 3)
print('Split array in 3 : \n',split_arr)

Original array:  [10 20 30 40 50 60]
Split array in 2 : 
 [array([10, 20, 30]), array([40, 50, 60])]
Split array in 3 : 
 [array([10, 20]), array([30, 40]), array([50, 60])]


In [13]:
# unique with counts

data = np.array([3,1,4,1,5,9,2,6,5,3,5])
vals, counts = np.unique(data,return_counts=True)
print('unique values:', vals)
print('counts        :', counts)

unique values: [1 2 3 4 5 6 9]
counts        : [2 1 2 1 3 1 1]


In [14]:
# argsort for ranking

scores = np.array([78,45,92,61,88,33,76])
names  = np.array(['Alice','Bob','Charlie','Diana','Eve','Frank','Grace'])
rank_order = np.argsort(scores)[::-1]
print('Ranking:')
for rank, idx in enumerate(rank_order,1):
    print(f'  {rank}. {names[idx]}: {scores[idx]}')

Ranking:
  1. Charlie: 92
  2. Eve: 88
  3. Alice: 78
  4. Grace: 76
  5. Diana: 61
  6. Bob: 45
  7. Frank: 33


In [15]:
# clip / round / flip / roll / tile / repeat / pad

raw = np.array([-5,0,23,105,88,-2,100])
print('clip(0,100) :', np.clip(raw,0,100))

x = np.array([1,2,3,4,5])
print('flip        :', np.flip(x))
print('roll +2     :', np.roll(x,2))
print('tile x2     :', np.tile(x,2))
print('repeat x2   :', np.repeat(x,2))
print('pad(0,w=2)  :', np.pad(x,2,constant_values=0))

clip(0,100) : [  0   0  23 100  88   0 100]
flip        : [5 4 3 2 1]
roll +2     : [4 5 1 2 3]
tile x2     : [1 2 3 4 5 1 2 3 4 5]
repeat x2   : [1 1 2 2 3 3 4 4 5 5]
pad(0,w=2)  : [0 0 1 2 3 4 5 0 0]
