## 9. Mathematical & Statistical Operations

### axis parameter
- `axis=None` → aggregate over **entire array**
- `axis=0` → aggregate **down rows** (per column)
- `axis=1` → aggregate **across columns** (per row)

### Universal Functions (ufuncs)
| Category | Functions |
|----------|-----------|
| Arithmetic | `np.add`, `np.multiply`, `np.power`, `np.mod` |
| Trig | `np.sin`, `np.cos`, `np.tan`, `np.deg2rad` |
| Exp/Log | `np.exp`, `np.log`, `np.log2`, `np.log10` |
| Rounding | `np.round`, `np.floor`, `np.ceil` |
| Compare | `np.maximum`, `np.minimum` |


In [10]:
import numpy as np
import math

In [19]:
# math
a = np.array([10,20,30])

print('a + 5   : ', a+5)
print('a - 5   : ', a-5)
print('a * 2   : ', a*2)
print('a ** 2  : ', a**2)
print('a % 2   : ', a%2)
print('a / 2   : ', a/2)
print('a // 2  : ', a//2)

a + 5   :  [15 25 35]
a - 5   :  [ 5 15 25]
a * 2   :  [20 40 60]
a ** 2  :  [100 400 900]
a % 2   :  [0 0 0]
a / 2   :  [ 5. 10. 15.]
a // 2  :  [ 5 10 15]


In [14]:
# Aggreate Function
arr = np.array([10,20,30,40,50])

print('max(arr)  : ', np.max(arr))
print('min(arr)  : ', np.min(arr))
print('mean(arr) : ', np.mean(arr))
print('sum(arr)  : ', np.sum(arr))
print('std(arr)  : ', np.std(arr))
print('var(arr)  : ', np.var(arr))

max(arr)  :  50
min(arr)  :  10
mean(arr) :  30.0
sum(arr)  :  150
std(arr)  :  14.142135623730951
var(arr)  :  200.0


In [20]:
# Aggregation with axis
m = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print('Matrix:\n', m)
print('sum all  :', m.sum())
print('sum axis0:', m.sum(axis=0))   # col sums
print('sum axis1:', m.sum(axis=1))   # row sums
print('cumsum row:\n', m.cumsum(axis=1))

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sum all  : 78
sum axis0: [15 18 21 24]
sum axis1: [10 26 42]
cumsum row:
 [[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]]


In [29]:
# Descriptive stats
rng    = np.random.default_rng(42)
scores = rng.normal(65,15,50).clip(0,100).round(1)

print(f'Mean  : {scores.mean():.2f}')
print(f'Median: {np.median(scores):.2f}')
print(f'Std   : {scores.std():.2f}')
print(f'Var   : {scores.var():.2f}')

Mean  : 66.37
Median: 67.60
Std   : 11.41
Var   : 130.16


In [32]:
# ufuncs
y = np.array([1.,2.,4.,8.])
print('y      :', y)

print('exp(y) :', np.exp(y).round(2))
print('log(y) :', np.log(y).round(3))
print('log2(y):', np.log2(y))
print('sqrt(y):', np.sqrt(y))

y      : [1. 2. 4. 8.]
exp(y) : [2.72000e+00 7.39000e+00 5.46000e+01 2.98096e+03]
log(y) : [0.    0.693 1.386 2.079]
log2(y): [0. 1. 2. 3.]
sqrt(y): [1.         1.41421356 2.         2.82842712]


In [38]:
# Correlation

hours_studied = np.array([1,2,3,4,5,6,7,8,9,10],dtype=float)
exam_score    = np.array([40,45,55,60,65,72,78,82,88,95],dtype=float)
corr = np.corrcoef(hours_studied, exam_score)
print('Pearson r :', corr[0,1].round(4))

Pearson r : 0.9977


In [37]:
# Histogram (text bar chart)

counts, bins = np.histogram(scores, bins=8)
print('Score distribution:')
for lo,hi,cnt in zip(bins,bins[1:],counts):
    print(f'  [{lo:5.1f}-{hi:5.1f}]: {"█"*cnt} ({cnt})')

Score distribution:
  [ 35.7- 43.4]: █ (1)
  [ 43.4- 51.0]: ███ (3)
  [ 51.0- 58.7]: █████████ (9)
  [ 58.7- 66.4]: ██████████ (10)
  [ 66.4- 74.1]: █████████████ (13)
  [ 74.1- 81.8]: ██████████ (10)
  [ 81.8- 89.4]: ███ (3)
  [ 89.4- 97.1]: █ (1)
